Repository wecode-bootcamp-korea/48-1st-C-frontend, pull requests merged in 2023-08, with the labels that each got.

#6 공통 컴포넌트 생성
  src/components/Button.jsx
  src/components/Input.jsx
Labels: 완료

#5 common css 스타일 추가
  public/favicon.ico
  public/index.html
  src/style/common.scss
Labels: 멘토 리뷰 요청, 완료

#2 README.md 추가
  README.md
Labels: 수정 요청, 완료
